services:
  - type: web
    name: presensi-ma-plus
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn dash.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: dash.settings
