# Generated by Django 4.2.21 on 2025-05-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='image_checkin',
            field=models.ImageField(blank=True, null=True, upload_to='presensi_images/'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='image_checkout',
            field=models.ImageField(blank=True, null=True, upload_to='presensi_images/'),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('guru', 'Guru')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='PengajuanIzin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('keterangan', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_izin', to='presensi.abstractuser')),
            ],
        ),
    ]
