# Generated by Django 4.2.21 on 2025-06-10 04:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0002_presensi_image_checkin_presensi_image_checkout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_masuk', models.TimeField(default=datetime.time(7, 0))),
                ('jam_pulang', models.TimeField(default=datetime.time(15, 0))),
                ('toleransi_terlambat', models.IntegerField(default=15)),
            ],
            options={
                'verbose_name_plural': 'Jam Kerja',
            },
        ),
        migrations.AlterModelOptions(
            name='pengajuanizin',
            options={'ordering': ['-tanggal_pengajuan']},
        ),
        migrations.AlterModelOptions(
            name='presensi',
            options={'ordering': ['-tanggal', '-jam_masuk']},
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pengajuanizin',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengajuanizin',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pengajuan', to='presensi.abstractuser'),
        ),
        migrations.AddField(
            model_name='pengajuanizin',
            name='jenis_izin',
            field=models.CharField(choices=[('izin', 'Izin'), ('sakit', 'Sakit'), ('cuti', 'Cuti')], default='izin', max_length=20),
        ),
        migrations.AddField(
            model_name='pengajuanizin',
            name='tanggal_approval',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengajuanizin',
            name='tanggal_pengajuan',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='presensi',
            name='jam_kerja_efektif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='presensi',
            name='lokasi_checkin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='presensi',
            name='lokasi_checkout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='presensi',
            name='terlambat_menit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('guru', 'Guru')], default='guru', max_length=20),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='status',
            field=models.CharField(choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpha', 'Alpha'), ('terlambat', 'Terlambat')], default='hadir', max_length=20),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
